/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FoodRouteImport } from './routes/food'
import { Route as BarRouteImport } from './routes/bar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCurateRouteImport } from './routes/api/curate'

const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const BarRoute = BarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurateRoute = ApiCurateRouteImport.update({
  id: '/api/curate',
  path: '/api/curate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bar': typeof BarRoute
  '/food': typeof FoodRoute
  '/api/curate': typeof ApiCurateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bar': typeof BarRoute
  '/food': typeof FoodRoute
  '/api/curate': typeof ApiCurateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bar': typeof BarRoute
  '/food': typeof FoodRoute
  '/api/curate': typeof ApiCurateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bar' | '/food' | '/api/curate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bar' | '/food' | '/api/curate'
  id: '__root__' | '/' | '/bar' | '/food' | '/api/curate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarRoute: typeof BarRoute
  FoodRoute: typeof FoodRoute
  ApiCurateRoute: typeof ApiCurateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bar': {
      id: '/bar'
      path: '/bar'
      fullPath: '/bar'
      preLoaderRoute: typeof BarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/curate': {
      id: '/api/curate'
      path: '/api/curate'
      fullPath: '/api/curate'
      preLoaderRoute: typeof ApiCurateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarRoute: BarRoute,
  FoodRoute: FoodRoute,
  ApiCurateRoute: ApiCurateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
